### ISSUE TITLE
demo 里面 放大缩小title错了

### ISSUE THREAD

**Issue by liuhuidi** [guozhaolong/wfd2-example#1]
![image](https://user-images.githubusercontent.com/29157036/86077734-1e69ee00-babf-11ea-939f-1cad28f239a2.png)

**Comment by guozhaolong** [comment]
多谢，这都被发现了。。。

**Comment by liuhuidi** [comment]
嘻嘻😁


| |
liuhuidi428
|
|
邮箱：liuhuidi428@163.com
|

Signature is customized by Netease Mail Master

在2020年07月02日 10:49，Steven Kwok 写道：

多谢，这都被发现了。。。

**Comment by liuhuidi** [comment]
i18n写错了，估计。


| |
liuhuidi428
|
|
邮箱：liuhuidi428@163.com
|

Signature is customized by Netease Mail Master

在2020年07月02日 10:49，Steven Kwok 写道：

Closed #1.
